# -*- coding: utf-8 -*-
"""ideale kook-eet ratio.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p7M2oXqAnoymDr-hPkki3XcUx23WVAJQ
"""

import streamlit as st
import math

st.title("Kook / Eet verhouding checker")

p = 0.31

# Vrije tekstinvoer
K_raw = st.text_input("Hoe vaak heb je gekookt?")
E_raw = st.text_input("Hoe vaak heb je meegegeten?")

# Controlefunctie
def is_int(value):
    try:
        int(value)
        return True
    except ValueError:
        return False

# Stop de app direct als iets fout is
if K_raw and not is_int(K_raw):
    st.error("Het aantal keren koken moet een geheel getal zijn.")
    st.stop()

if E_raw and not is_int(E_raw):
    st.error("Het aantal keren mee-eten moet een geheel getal zijn.")
    st.stop()

# Alleen doorgaan als beide velden geldig zijn én ingevuld
if K_raw and E_raw:
    K = int(K_raw)
    E = int(E_raw)

    def find_kook_eet_strat(p, K, E):
        p_min = p - 0.005
        p_max = p + 0.004

        if (K / E) > 1:
            st.error("Hoe kun je vaker gekookt hebben dan meegegeten?")
            return

        x = math.ceil((p_min * E - K) / (1 - p_min))

        if x <= 0:
            st.success("Je verhouding is al minstens 0.31!")
        else:
            st.info(f"Je moet minstens {x} keer koken om op een verhouding van 0.31 of hoger te staan.")

        x_min = (p_min * E - K) / (1 - p_min)
        x_max = (p_max * E - K) / (1 - p_max)

        if x_min >= 0 and (x_max - x_min) >= 1:
            if (x_max - x_min) > 50:
                st.warning("Er zijn te veel mogelijkheden om netjes te tonen.")
                return
            x_min_int = math.ceil(x_min)
            x_max_int = math.floor(x_max)

            keren_koken = list(range(x_min_int, x_max_int + 1))

            if len(keren_koken) == 1:
                st.write(f"Je kunt exact op 0.31 staan door {keren_koken[0]} keer te koken.")
            elif len(keren_koken) == 2:
                st.write(f"Je kunt exact op 0.31 staan door {keren_koken[0]} of {keren_koken[1]} keer te koken.")
            else:
                opties = ", ".join(map(str, keren_koken[:-1])) + f" of {keren_koken[-1]}"
                st.write(f"Je kunt exact op 0.31 staan door {opties} keer te koken.")
        else:
            for i in range(0, 31):
                for j in range(0, 31):
                    totaal_koken = K + i
                    totaal_eten = E + i + j
                    verhouding = totaal_koken / totaal_eten
                    if p_min <= verhouding <= p_max:
                        st.write(f"Je moet minstens {i} keer koken en {j} keer extra mee-eten om op 0.31 te komen.")
                        return
            st.warning("Geen oplossing gevonden binnen 30 keer koken/mee-eten.")

    find_kook_eet_strat(p, K, E)
